name: Auto WebSite Update

on: [push]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: List directory contents
      run: ls -la ./DataSaturdaysWebsite/
      shell: bash

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0'

    - name: Restore NuGet packages for DataSaturdaysWebsite
      run: dotnet restore ./DataSaturdaysWebsite/DataSaturdaysWebsite.csproj

    - name: Build DataSaturdaysWebsite with MSBuild
      run: |
        $msbuildPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
        & $msbuildPath ./DataSaturdaysWebsite/DataSaturdaysWebsite.csproj /p:Configuration=Release /p:Platform="Any CPU" /m
      shell: pwsh

      

